version: '3'

services: 
  myredis:
    image: 'redis:alpine'
  mypostgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=telescopes
    volumes:
      - G:/postgresdata:/var/lib/postgresql/data
  mybackend:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./mybackend
    volumes: 
      - /opt/app/node_modules
      - C:/Users/Rafal/Desktop/Docker/webapp/mybackend:/opt/app
    environment: 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=telescopes
      - POSTGRES_USER=docker
      - REDIS_HOST=myredis
      - POSTGRES_HOST=mypostgres
    ports:
      - "5000:4000"
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
      - "9090:80"
  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - /opt/app/node_modules
      - C:/Users/Rafal/Desktop/Docker/webapp/myfrontend:/opt/app

