apiVersion: v1
kind: Service
metadata:
  name: my-backendlb-node-port

spec:
  type: NodePort
  ports: 
    - port: 7000
      targetPort: 7000
      nodePort: 31100

  selector:
    component: backend
    app: my-app