apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    component: web
    app: my-app-1

spec: 
  containers: 
    - name: my-nginx
      image: ceoael/mynginx
      ports:
        - containerPort: 80
