apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    component: web
    app: my-app-1

spec:
  template:
    metadata:
      name: my-nginx-pod
      labels:
        component: web
        app: my-app-1
    spec:
      containers:
        - name: my-nginx-container
          image: ceoael/mynginx

  replicas: 3
  selector:
    matchLabels:
      app: my-app-1
      component: web