apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # it will create persistent volume in disk g in folder myapp_pv
    path: /run/desktop/mnt/host/g/myapp_pv
